imports:
    - { resource: config.yml }
framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        handler_id: ~
web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"
twig:
    cache: false
    globals:
        #JS_PATH: %REMOTE_JS_URL%
        IMG_PATH: %REMOTE_PIC_URL%
        STATIC_PATH: %WEB_CDN_STATIC%
        PICTURE_CDN_PATH: %PIC_CDN_STATIC%
#snc_redis:
#    clients:
#        default:
#            type: predis
#            alias: default
#            dsn:
#              - redis://%REDIS_CLI_IP_PORT%/1
#            logging: false
#        cache:
#            type: predis
#            alias: cache
#            dsn: redis://%REDIS_CLI_IP_PORT%/1
#            logging: false
#    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: default
#            document_manager: default
        #result_cache:
         #  client: cache
         #  entity_manager: [default, read]
         #  document_manager: [default]
         #  namespace: "dcrc:"
        #query_cache:
         #   client: cache
         #   entity_manager: default
