# 支付相关的配置
parameters:
    #接口名称,发送支付申请(选银行)
    PAY_SERVICE_CODE: FC0028
    #版本
    PAY_VERSION: "1.0"
    #接口类型
    PAY_SERVICE_TYPE: "03"
    #签名类型
    PAY_SIGNTYPE: md5
    #平台编码
    PAY_SYSPLATCODE: V
    #编码
    PAY_CHARSET: utf-8
    #通知地址
    PAY_NOTICE_URL: /charge/notice
    #回调地址
    PAY_REBACK_URL: /charge/reback

    #写日志的文件
    PAY_LOG_FILE: /tmp/video_charge_callback.log

    #补钱地址
    PAY_REPAY_URL: /charge/callFailOrder
    #接口名称,发送查询申请
    PAY_FIND_CODE: FC0029
    #配置活动开启
    ACTIVITY_OPEN: 1
    #配置活动
    ACTIVITY_NAME: "firstcharge"
    #活动接口地址
    ACTIVITY_URL: /activitySend
    #支付渠道
    PAY_CHANNEL:
      "xs": "NP" #第一个新生，
      "hx": "IPS" #第二个环迅
      "sf": "SF" #第三个顺峰
    #首页存放userinfo的数据的cookie键
    #VF_USER_INDEX: vf_user_index
    SEND_GIFT_EXPIRE: 2014-01-01/2015-03-01
    #用户推广链接活动开关,1=开,0=关
    INVITATION_STATUS: 0
    #用户注册送礼
    REG_SEND_STATUS: 1
    #首充活动开关
    FIRST_RECHARGE_STATUS: 1
    #赠送抽奖机会开关
    LOTTRY_STATUS: 1
    #登录送的钱数
    LOGIN_SEND_POINT: 100
    SERVICE_ONLINE_TYPE: ["登陆注册类","充值提款类","优惠活动类","客服服务类","投诉意见类"]
    #注册送的钱数
    REGISTER_SEND_POINT: 500
    #记录密码登录的密钥key,VideoBaseController要保持一致
    WEB_SECRET_KEY: c5ff645187eb7245d43178f20607920e456